### ISSUE TITLE
ISO-18245 codes.json is missing in NuGet Package

### ISSUE THREAD

**Issue by fabich** [maisak/iso.resolvers#1]
Hi maisak

First of all, thanks a lot for this lib.
That's exactly what I have been looking for!

Unfortunately, there is an error when using your lib via NuGet:
`FileNotFoundException: Could not find file '.........\bin\Debug\netcoreapp2.2\codes.json'.`

Could you please have a look if the file gets added to the lib on NuGet?

**Comment by maisak** [comment]
Sorry for the delay @fabich. It is already fixed.

**Comment by fabich** [comment]
I installed ISO.18245.MerchantCategoryCodes v1.0.3 via NuGet.
When running the application I still get a FileNotFoundException.

Is there anything else I need to do?

**Comment by maisak** [comment]
To workaround, just copy [this file](https://github.com/maisak/iso.resolvers/blob/master/src/ISO.18245/codes.json) to the output folder of your project. Meanwhile, I will check on why it is not copied automatically.

**Comment by fabich** [comment]
That's what I did in the meantime, works well.

**Comment by maisak** [comment]
BTW, what is the environment you use? I see a problem on Linux, but in Windows environment it seems to be ok.

**Comment by fabich** [comment]
windows 10 Pro, version 1903
Visual Studio 16.3.7
netcoreapp2.2

**Comment by maisak** [comment]
Can you do `nuget locals all -clear` in console? This should clear local nuget cache at C:\Users\%Username%\.nuget.

**Comment by maisak** [comment]
Ok, guess, I figured it out, version 1.0.4 should be ok for you. Should have used $(ProjectDir) instead of $(SolutionDir), this caused that file was not copied in projects where solution file and a project file were not in the same directory.

**Comment by fabich** [comment]
works now
